//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /work/sphereScript99.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public partial class sphereScript99Lexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, NEWLINE=6, WS=7, EOF_SECTION_HEADER=8, 
		FUNCTION_SECTION_HEADER_START=9, IF=10, ELSEIF=11, ELSE=12, ENDIF=13, 
		NATIVE_FUNCTIONS=14, SYSMESSAGE=15, RETURN=16, TIMER=17, CONSUME=18, EVAL_FUNCTIONS=19, 
		EVAL=20, HVAL=21, SAFE=22, SYMBOL=23, NUMBER=24, EQUAL=25, ASSIGN=26, 
		NOT_EQUAL=27, MORE_THAN=28, LESS_THAN=29, PLUS=30, MINUS=31, MULTIPLY=32, 
		MORE_THAN_EQUAL=33, LESS_THAN_EQUAL=34, LPAREN=35, RPAREN=36;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "NEWLINE", "WS", "EOF_SECTION_HEADER", 
		"FUNCTION_SECTION_HEADER_START", "IF", "ELSEIF", "ELSE", "ENDIF", "NATIVE_FUNCTIONS", 
		"SYSMESSAGE", "RETURN", "TIMER", "CONSUME", "EVAL_FUNCTIONS", "EVAL", 
		"HVAL", "SAFE", "SYMBOL", "NUMBER", "EQUAL", "ASSIGN", "NOT_EQUAL", "MORE_THAN", 
		"LESS_THAN", "PLUS", "MINUS", "MULTIPLY", "MORE_THAN_EQUAL", "LESS_THAN_EQUAL", 
		"VALID_SYMBOL_START", "VALID_SYMBOL_CHAR", "DIGIT", "LPAREN", "RPAREN"
	};


	public sphereScript99Lexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public sphereScript99Lexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "']'", "'.'", "','", "'\"'", "'['", null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, "'=='", "'='", "'!='", "'>'", "'<'", "'+'", "'-'", "'*'", 
		null, null, "'('", "')'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, "NEWLINE", "WS", "EOF_SECTION_HEADER", 
		"FUNCTION_SECTION_HEADER_START", "IF", "ELSEIF", "ELSE", "ENDIF", "NATIVE_FUNCTIONS", 
		"SYSMESSAGE", "RETURN", "TIMER", "CONSUME", "EVAL_FUNCTIONS", "EVAL", 
		"HVAL", "SAFE", "SYMBOL", "NUMBER", "EQUAL", "ASSIGN", "NOT_EQUAL", "MORE_THAN", 
		"LESS_THAN", "PLUS", "MINUS", "MULTIPLY", "MORE_THAN_EQUAL", "LESS_THAN_EQUAL", 
		"LPAREN", "RPAREN"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "sphereScript99.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static sphereScript99Lexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '&', '\xFA', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x4', '$', '\t', '$', '\x4', '%', '\t', '%', '\x4', '&', 
		'\t', '&', '\x4', '\'', '\t', '\'', '\x4', '(', '\t', '(', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x5', 
		'\a', ']', '\n', '\a', '\x3', '\a', '\x6', '\a', '`', '\n', '\a', '\r', 
		'\a', '\xE', '\a', '\x61', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x6', '\n', 
		'w', '\n', '\n', '\r', '\n', '\xE', '\n', 'x', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x5', '\xF', '\x94', '\n', '\xF', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', 
		'\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', 
		'\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x5', '\x14', 
		'\xB9', '\n', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', 
		'\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', 
		'\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', 
		'\x17', '\x3', '\x17', '\x3', '\x18', '\x3', '\x18', '\a', '\x18', '\xCC', 
		'\n', '\x18', '\f', '\x18', '\xE', '\x18', '\xCF', '\v', '\x18', '\x3', 
		'\x19', '\x6', '\x19', '\xD2', '\n', '\x19', '\r', '\x19', '\xE', '\x19', 
		'\xD3', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x3', 
		'\x1B', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1D', '\x3', 
		'\x1D', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1F', '\x3', '\x1F', '\x3', 
		' ', '\x3', ' ', '\x3', '!', '\x3', '!', '\x3', '\"', '\x3', '\"', '\x3', 
		'\"', '\x3', '#', '\x3', '#', '\x3', '#', '\x3', '$', '\x5', '$', '\xEF', 
		'\n', '$', '\x3', '%', '\x3', '%', '\x5', '%', '\xF3', '\n', '%', '\x3', 
		'&', '\x3', '&', '\x3', '\'', '\x3', '\'', '\x3', '(', '\x3', '(', '\x2', 
		'\x2', ')', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', 
		'\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', 
		'\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', 
		'!', '\x12', '#', '\x13', '%', '\x14', '\'', '\x15', ')', '\x16', '+', 
		'\x17', '-', '\x18', '/', '\x19', '\x31', '\x1A', '\x33', '\x1B', '\x35', 
		'\x1C', '\x37', '\x1D', '\x39', '\x1E', ';', '\x1F', '=', ' ', '?', '!', 
		'\x41', '\"', '\x43', '#', '\x45', '$', 'G', '\x2', 'I', '\x2', 'K', '\x2', 
		'M', '%', 'O', '&', '\x3', '\x2', '\x16', '\x4', '\x2', '\v', '\v', '\"', 
		'\"', '\x4', '\x2', 'G', 'G', 'g', 'g', '\x4', '\x2', 'Q', 'Q', 'q', 'q', 
		'\x4', '\x2', 'H', 'H', 'h', 'h', '\x4', '\x2', 'K', 'K', 'k', 'k', '\x4', 
		'\x2', 'N', 'N', 'n', 'n', '\x4', '\x2', 'U', 'U', 'u', 'u', '\x4', '\x2', 
		'P', 'P', 'p', 'p', '\x4', '\x2', '\x46', '\x46', '\x66', '\x66', '\x4', 
		'\x2', '[', '[', '{', '{', '\x4', '\x2', 'O', 'O', 'o', 'o', '\x4', '\x2', 
		'\x43', '\x43', '\x63', '\x63', '\x4', '\x2', 'I', 'I', 'i', 'i', '\x4', 
		'\x2', 'T', 'T', 't', 't', '\x4', '\x2', 'V', 'V', 'v', 'v', '\x4', '\x2', 
		'W', 'W', 'w', 'w', '\x4', '\x2', '\x45', '\x45', '\x65', '\x65', '\x4', 
		'\x2', 'X', 'X', 'x', 'x', '\x4', '\x2', 'J', 'J', 'j', 'j', '\x5', '\x2', 
		'\x43', '\\', '\x61', '\x61', '\x63', '|', '\x2', '\x101', '\x2', '\x3', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x31', '\x3', '\x2', '\x2', '\x2', '\x2', '\x33', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x35', '\x3', '\x2', '\x2', '\x2', '\x2', '\x37', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x39', '\x3', '\x2', '\x2', '\x2', '\x2', 
		';', '\x3', '\x2', '\x2', '\x2', '\x2', '=', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '?', '\x3', '\x2', '\x2', '\x2', '\x2', '\x41', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x43', '\x3', '\x2', '\x2', '\x2', '\x2', '\x45', '\x3', 
		'\x2', '\x2', '\x2', '\x2', 'M', '\x3', '\x2', '\x2', '\x2', '\x2', 'O', 
		'\x3', '\x2', '\x2', '\x2', '\x3', 'Q', '\x3', '\x2', '\x2', '\x2', '\x5', 
		'S', '\x3', '\x2', '\x2', '\x2', '\a', 'U', '\x3', '\x2', '\x2', '\x2', 
		'\t', 'W', '\x3', '\x2', '\x2', '\x2', '\v', 'Y', '\x3', '\x2', '\x2', 
		'\x2', '\r', '_', '\x3', '\x2', '\x2', '\x2', '\xF', '\x63', '\x3', '\x2', 
		'\x2', '\x2', '\x11', '\x65', '\x3', '\x2', '\x2', '\x2', '\x13', 'k', 
		'\x3', '\x2', '\x2', '\x2', '\x15', 'z', '\x3', '\x2', '\x2', '\x2', '\x17', 
		'}', '\x3', '\x2', '\x2', '\x2', '\x19', '\x84', '\x3', '\x2', '\x2', 
		'\x2', '\x1B', '\x89', '\x3', '\x2', '\x2', '\x2', '\x1D', '\x93', '\x3', 
		'\x2', '\x2', '\x2', '\x1F', '\x95', '\x3', '\x2', '\x2', '\x2', '!', 
		'\xA0', '\x3', '\x2', '\x2', '\x2', '#', '\xA7', '\x3', '\x2', '\x2', 
		'\x2', '%', '\xAD', '\x3', '\x2', '\x2', '\x2', '\'', '\xB8', '\x3', '\x2', 
		'\x2', '\x2', ')', '\xBA', '\x3', '\x2', '\x2', '\x2', '+', '\xBF', '\x3', 
		'\x2', '\x2', '\x2', '-', '\xC4', '\x3', '\x2', '\x2', '\x2', '/', '\xC9', 
		'\x3', '\x2', '\x2', '\x2', '\x31', '\xD1', '\x3', '\x2', '\x2', '\x2', 
		'\x33', '\xD5', '\x3', '\x2', '\x2', '\x2', '\x35', '\xD8', '\x3', '\x2', 
		'\x2', '\x2', '\x37', '\xDA', '\x3', '\x2', '\x2', '\x2', '\x39', '\xDD', 
		'\x3', '\x2', '\x2', '\x2', ';', '\xDF', '\x3', '\x2', '\x2', '\x2', '=', 
		'\xE1', '\x3', '\x2', '\x2', '\x2', '?', '\xE3', '\x3', '\x2', '\x2', 
		'\x2', '\x41', '\xE5', '\x3', '\x2', '\x2', '\x2', '\x43', '\xE7', '\x3', 
		'\x2', '\x2', '\x2', '\x45', '\xEA', '\x3', '\x2', '\x2', '\x2', 'G', 
		'\xEE', '\x3', '\x2', '\x2', '\x2', 'I', '\xF2', '\x3', '\x2', '\x2', 
		'\x2', 'K', '\xF4', '\x3', '\x2', '\x2', '\x2', 'M', '\xF6', '\x3', '\x2', 
		'\x2', '\x2', 'O', '\xF8', '\x3', '\x2', '\x2', '\x2', 'Q', 'R', '\a', 
		'_', '\x2', '\x2', 'R', '\x4', '\x3', '\x2', '\x2', '\x2', 'S', 'T', '\a', 
		'\x30', '\x2', '\x2', 'T', '\x6', '\x3', '\x2', '\x2', '\x2', 'U', 'V', 
		'\a', '.', '\x2', '\x2', 'V', '\b', '\x3', '\x2', '\x2', '\x2', 'W', 'X', 
		'\a', '$', '\x2', '\x2', 'X', '\n', '\x3', '\x2', '\x2', '\x2', 'Y', 'Z', 
		'\a', ']', '\x2', '\x2', 'Z', '\f', '\x3', '\x2', '\x2', '\x2', '[', ']', 
		'\a', '\xF', '\x2', '\x2', '\\', '[', '\x3', '\x2', '\x2', '\x2', '\\', 
		']', '\x3', '\x2', '\x2', '\x2', ']', '^', '\x3', '\x2', '\x2', '\x2', 
		'^', '`', '\a', '\f', '\x2', '\x2', '_', '\\', '\x3', '\x2', '\x2', '\x2', 
		'`', '\x61', '\x3', '\x2', '\x2', '\x2', '\x61', '_', '\x3', '\x2', '\x2', 
		'\x2', '\x61', '\x62', '\x3', '\x2', '\x2', '\x2', '\x62', '\xE', '\x3', 
		'\x2', '\x2', '\x2', '\x63', '\x64', '\t', '\x2', '\x2', '\x2', '\x64', 
		'\x10', '\x3', '\x2', '\x2', '\x2', '\x65', '\x66', '\a', ']', '\x2', 
		'\x2', '\x66', 'g', '\t', '\x3', '\x2', '\x2', 'g', 'h', '\t', '\x4', 
		'\x2', '\x2', 'h', 'i', '\t', '\x5', '\x2', '\x2', 'i', 'j', '\a', '_', 
		'\x2', '\x2', 'j', '\x12', '\x3', '\x2', '\x2', '\x2', 'k', 'l', '\a', 
		']', '\x2', '\x2', 'l', 'm', '\a', 'h', '\x2', '\x2', 'm', 'n', '\a', 
		'w', '\x2', '\x2', 'n', 'o', '\a', 'p', '\x2', '\x2', 'o', 'p', '\a', 
		'\x65', '\x2', '\x2', 'p', 'q', '\a', 'v', '\x2', '\x2', 'q', 'r', '\a', 
		'k', '\x2', '\x2', 'r', 's', '\a', 'q', '\x2', '\x2', 's', 't', '\a', 
		'p', '\x2', '\x2', 't', 'v', '\x3', '\x2', '\x2', '\x2', 'u', 'w', '\x5', 
		'\xF', '\b', '\x2', 'v', 'u', '\x3', '\x2', '\x2', '\x2', 'w', 'x', '\x3', 
		'\x2', '\x2', '\x2', 'x', 'v', '\x3', '\x2', '\x2', '\x2', 'x', 'y', '\x3', 
		'\x2', '\x2', '\x2', 'y', '\x14', '\x3', '\x2', '\x2', '\x2', 'z', '{', 
		'\t', '\x6', '\x2', '\x2', '{', '|', '\t', '\x5', '\x2', '\x2', '|', '\x16', 
		'\x3', '\x2', '\x2', '\x2', '}', '~', '\t', '\x3', '\x2', '\x2', '~', 
		'\x7F', '\t', '\a', '\x2', '\x2', '\x7F', '\x80', '\t', '\b', '\x2', '\x2', 
		'\x80', '\x81', '\t', '\x3', '\x2', '\x2', '\x81', '\x82', '\t', '\x6', 
		'\x2', '\x2', '\x82', '\x83', '\t', '\x5', '\x2', '\x2', '\x83', '\x18', 
		'\x3', '\x2', '\x2', '\x2', '\x84', '\x85', '\t', '\x3', '\x2', '\x2', 
		'\x85', '\x86', '\t', '\a', '\x2', '\x2', '\x86', '\x87', '\t', '\b', 
		'\x2', '\x2', '\x87', '\x88', '\t', '\x3', '\x2', '\x2', '\x88', '\x1A', 
		'\x3', '\x2', '\x2', '\x2', '\x89', '\x8A', '\t', '\x3', '\x2', '\x2', 
		'\x8A', '\x8B', '\t', '\t', '\x2', '\x2', '\x8B', '\x8C', '\t', '\n', 
		'\x2', '\x2', '\x8C', '\x8D', '\t', '\x6', '\x2', '\x2', '\x8D', '\x8E', 
		'\t', '\x5', '\x2', '\x2', '\x8E', '\x1C', '\x3', '\x2', '\x2', '\x2', 
		'\x8F', '\x94', '\x5', '\x1F', '\x10', '\x2', '\x90', '\x94', '\x5', '!', 
		'\x11', '\x2', '\x91', '\x94', '\x5', '#', '\x12', '\x2', '\x92', '\x94', 
		'\x5', '%', '\x13', '\x2', '\x93', '\x8F', '\x3', '\x2', '\x2', '\x2', 
		'\x93', '\x90', '\x3', '\x2', '\x2', '\x2', '\x93', '\x91', '\x3', '\x2', 
		'\x2', '\x2', '\x93', '\x92', '\x3', '\x2', '\x2', '\x2', '\x94', '\x1E', 
		'\x3', '\x2', '\x2', '\x2', '\x95', '\x96', '\t', '\b', '\x2', '\x2', 
		'\x96', '\x97', '\t', '\v', '\x2', '\x2', '\x97', '\x98', '\t', '\b', 
		'\x2', '\x2', '\x98', '\x99', '\t', '\f', '\x2', '\x2', '\x99', '\x9A', 
		'\t', '\x3', '\x2', '\x2', '\x9A', '\x9B', '\t', '\b', '\x2', '\x2', '\x9B', 
		'\x9C', '\t', '\b', '\x2', '\x2', '\x9C', '\x9D', '\t', '\r', '\x2', '\x2', 
		'\x9D', '\x9E', '\t', '\xE', '\x2', '\x2', '\x9E', '\x9F', '\t', '\x3', 
		'\x2', '\x2', '\x9F', ' ', '\x3', '\x2', '\x2', '\x2', '\xA0', '\xA1', 
		'\t', '\xF', '\x2', '\x2', '\xA1', '\xA2', '\t', '\x3', '\x2', '\x2', 
		'\xA2', '\xA3', '\t', '\x10', '\x2', '\x2', '\xA3', '\xA4', '\t', '\x11', 
		'\x2', '\x2', '\xA4', '\xA5', '\t', '\xF', '\x2', '\x2', '\xA5', '\xA6', 
		'\t', '\t', '\x2', '\x2', '\xA6', '\"', '\x3', '\x2', '\x2', '\x2', '\xA7', 
		'\xA8', '\t', '\x10', '\x2', '\x2', '\xA8', '\xA9', '\t', '\x6', '\x2', 
		'\x2', '\xA9', '\xAA', '\t', '\f', '\x2', '\x2', '\xAA', '\xAB', '\t', 
		'\x3', '\x2', '\x2', '\xAB', '\xAC', '\t', '\xF', '\x2', '\x2', '\xAC', 
		'$', '\x3', '\x2', '\x2', '\x2', '\xAD', '\xAE', '\t', '\x12', '\x2', 
		'\x2', '\xAE', '\xAF', '\t', '\x4', '\x2', '\x2', '\xAF', '\xB0', '\t', 
		'\t', '\x2', '\x2', '\xB0', '\xB1', '\t', '\b', '\x2', '\x2', '\xB1', 
		'\xB2', '\t', '\x11', '\x2', '\x2', '\xB2', '\xB3', '\t', '\f', '\x2', 
		'\x2', '\xB3', '\xB4', '\t', '\x3', '\x2', '\x2', '\xB4', '&', '\x3', 
		'\x2', '\x2', '\x2', '\xB5', '\xB9', '\x5', ')', '\x15', '\x2', '\xB6', 
		'\xB9', '\x5', '+', '\x16', '\x2', '\xB7', '\xB9', '\x5', '-', '\x17', 
		'\x2', '\xB8', '\xB5', '\x3', '\x2', '\x2', '\x2', '\xB8', '\xB6', '\x3', 
		'\x2', '\x2', '\x2', '\xB8', '\xB7', '\x3', '\x2', '\x2', '\x2', '\xB9', 
		'(', '\x3', '\x2', '\x2', '\x2', '\xBA', '\xBB', '\t', '\x3', '\x2', '\x2', 
		'\xBB', '\xBC', '\t', '\x13', '\x2', '\x2', '\xBC', '\xBD', '\t', '\r', 
		'\x2', '\x2', '\xBD', '\xBE', '\t', '\a', '\x2', '\x2', '\xBE', '*', '\x3', 
		'\x2', '\x2', '\x2', '\xBF', '\xC0', '\t', '\x14', '\x2', '\x2', '\xC0', 
		'\xC1', '\t', '\x13', '\x2', '\x2', '\xC1', '\xC2', '\t', '\r', '\x2', 
		'\x2', '\xC2', '\xC3', '\t', '\a', '\x2', '\x2', '\xC3', ',', '\x3', '\x2', 
		'\x2', '\x2', '\xC4', '\xC5', '\t', '\b', '\x2', '\x2', '\xC5', '\xC6', 
		'\t', '\r', '\x2', '\x2', '\xC6', '\xC7', '\t', '\x5', '\x2', '\x2', '\xC7', 
		'\xC8', '\t', '\x3', '\x2', '\x2', '\xC8', '.', '\x3', '\x2', '\x2', '\x2', 
		'\xC9', '\xCD', '\x5', 'G', '$', '\x2', '\xCA', '\xCC', '\x5', 'I', '%', 
		'\x2', '\xCB', '\xCA', '\x3', '\x2', '\x2', '\x2', '\xCC', '\xCF', '\x3', 
		'\x2', '\x2', '\x2', '\xCD', '\xCB', '\x3', '\x2', '\x2', '\x2', '\xCD', 
		'\xCE', '\x3', '\x2', '\x2', '\x2', '\xCE', '\x30', '\x3', '\x2', '\x2', 
		'\x2', '\xCF', '\xCD', '\x3', '\x2', '\x2', '\x2', '\xD0', '\xD2', '\x5', 
		'K', '&', '\x2', '\xD1', '\xD0', '\x3', '\x2', '\x2', '\x2', '\xD2', '\xD3', 
		'\x3', '\x2', '\x2', '\x2', '\xD3', '\xD1', '\x3', '\x2', '\x2', '\x2', 
		'\xD3', '\xD4', '\x3', '\x2', '\x2', '\x2', '\xD4', '\x32', '\x3', '\x2', 
		'\x2', '\x2', '\xD5', '\xD6', '\a', '?', '\x2', '\x2', '\xD6', '\xD7', 
		'\a', '?', '\x2', '\x2', '\xD7', '\x34', '\x3', '\x2', '\x2', '\x2', '\xD8', 
		'\xD9', '\a', '?', '\x2', '\x2', '\xD9', '\x36', '\x3', '\x2', '\x2', 
		'\x2', '\xDA', '\xDB', '\a', '#', '\x2', '\x2', '\xDB', '\xDC', '\a', 
		'?', '\x2', '\x2', '\xDC', '\x38', '\x3', '\x2', '\x2', '\x2', '\xDD', 
		'\xDE', '\a', '@', '\x2', '\x2', '\xDE', ':', '\x3', '\x2', '\x2', '\x2', 
		'\xDF', '\xE0', '\a', '>', '\x2', '\x2', '\xE0', '<', '\x3', '\x2', '\x2', 
		'\x2', '\xE1', '\xE2', '\a', '-', '\x2', '\x2', '\xE2', '>', '\x3', '\x2', 
		'\x2', '\x2', '\xE3', '\xE4', '\a', '/', '\x2', '\x2', '\xE4', '@', '\x3', 
		'\x2', '\x2', '\x2', '\xE5', '\xE6', '\a', ',', '\x2', '\x2', '\xE6', 
		'\x42', '\x3', '\x2', '\x2', '\x2', '\xE7', '\xE8', '\x5', '\x39', '\x1D', 
		'\x2', '\xE8', '\xE9', '\x5', '\x35', '\x1B', '\x2', '\xE9', '\x44', '\x3', 
		'\x2', '\x2', '\x2', '\xEA', '\xEB', '\x5', ';', '\x1E', '\x2', '\xEB', 
		'\xEC', '\x5', '\x35', '\x1B', '\x2', '\xEC', '\x46', '\x3', '\x2', '\x2', 
		'\x2', '\xED', '\xEF', '\t', '\x15', '\x2', '\x2', '\xEE', '\xED', '\x3', 
		'\x2', '\x2', '\x2', '\xEF', 'H', '\x3', '\x2', '\x2', '\x2', '\xF0', 
		'\xF3', '\x5', 'G', '$', '\x2', '\xF1', '\xF3', '\x5', 'K', '&', '\x2', 
		'\xF2', '\xF0', '\x3', '\x2', '\x2', '\x2', '\xF2', '\xF1', '\x3', '\x2', 
		'\x2', '\x2', '\xF3', 'J', '\x3', '\x2', '\x2', '\x2', '\xF4', '\xF5', 
		'\x4', '\x32', ';', '\x2', '\xF5', 'L', '\x3', '\x2', '\x2', '\x2', '\xF6', 
		'\xF7', '\a', '*', '\x2', '\x2', '\xF7', 'N', '\x3', '\x2', '\x2', '\x2', 
		'\xF8', '\xF9', '\a', '+', '\x2', '\x2', '\xF9', 'P', '\x3', '\x2', '\x2', 
		'\x2', '\f', '\x2', '\\', '\x61', 'x', '\x93', '\xB8', '\xCD', '\xD3', 
		'\xEE', '\xF2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
