//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /mnt/c/Users/jakub/sources/ultima/SphereSharp/SphereSharp/src/SphereSharp/sphereScript99.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="sphereScript99Parser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public interface IsphereScript99Visitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.macro"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacro([NotNull] sphereScript99Parser.MacroContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCall([NotNull] sphereScript99Parser.CallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumentList([NotNull] sphereScript99Parser.ArgumentListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument([NotNull] sphereScript99Parser.ArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.expressionArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionArgument([NotNull] sphereScript99Parser.ExpressionArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.unquotedLiteralArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnquotedLiteralArgument([NotNull] sphereScript99Parser.UnquotedLiteralArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.signedOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSignedOperand([NotNull] sphereScript99Parser.SignedOperandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.operand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperand([NotNull] sphereScript99Parser.OperandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.binaryOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryOperation([NotNull] sphereScript99Parser.BinaryOperationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperator([NotNull] sphereScript99Parser.OperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.constantExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantExpression([NotNull] sphereScript99Parser.ConstantExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.macroExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacroExpression([NotNull] sphereScript99Parser.MacroExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.subExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubExpression([NotNull] sphereScript99Parser.SubExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.macroOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacroOperator([NotNull] sphereScript99Parser.MacroOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.constantOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantOperator([NotNull] sphereScript99Parser.ConstantOperatorContext context);
}
