//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /work/sphereScript99.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IsphereScript99Listener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public partial class sphereScript99BaseListener : IsphereScript99Listener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFile([NotNull] sphereScript99Parser.FileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFile([NotNull] sphereScript99Parser.FileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSection([NotNull] sphereScript99Parser.SectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.section"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSection([NotNull] sphereScript99Parser.SectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.eofSection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEofSection([NotNull] sphereScript99Parser.EofSectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.eofSection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEofSection([NotNull] sphereScript99Parser.EofSectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.functionSection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionSection([NotNull] sphereScript99Parser.FunctionSectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.functionSection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionSection([NotNull] sphereScript99Parser.FunctionSectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.functionSectionHeader"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionSectionHeader([NotNull] sphereScript99Parser.FunctionSectionHeaderContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.functionSectionHeader"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionSectionHeader([NotNull] sphereScript99Parser.FunctionSectionHeaderContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.codeBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCodeBlock([NotNull] sphereScript99Parser.CodeBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.codeBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCodeBlock([NotNull] sphereScript99Parser.CodeBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] sphereScript99Parser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] sphereScript99Parser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] sphereScript99Parser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] sphereScript99Parser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.elseIfStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseIfStatement([NotNull] sphereScript99Parser.ElseIfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.elseIfStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseIfStatement([NotNull] sphereScript99Parser.ElseIfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.elseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseStatement([NotNull] sphereScript99Parser.ElseStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.elseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseStatement([NotNull] sphereScript99Parser.ElseStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.macro"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMacro([NotNull] sphereScript99Parser.MacroContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.macro"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMacro([NotNull] sphereScript99Parser.MacroContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCall([NotNull] sphereScript99Parser.CallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCall([NotNull] sphereScript99Parser.CallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] sphereScript99Parser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] sphereScript99Parser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.memberAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemberAccess([NotNull] sphereScript99Parser.MemberAccessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.memberAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemberAccess([NotNull] sphereScript99Parser.MemberAccessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.chainedMemberAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChainedMemberAccess([NotNull] sphereScript99Parser.ChainedMemberAccessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.chainedMemberAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChainedMemberAccess([NotNull] sphereScript99Parser.ChainedMemberAccessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.memberName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemberName([NotNull] sphereScript99Parser.MemberNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.memberName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemberName([NotNull] sphereScript99Parser.MemberNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.enclosedArgumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnclosedArgumentList([NotNull] sphereScript99Parser.EnclosedArgumentListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.enclosedArgumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnclosedArgumentList([NotNull] sphereScript99Parser.EnclosedArgumentListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.argumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentList([NotNull] sphereScript99Parser.ArgumentListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.argumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentList([NotNull] sphereScript99Parser.ArgumentListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgument([NotNull] sphereScript99Parser.ArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgument([NotNull] sphereScript99Parser.ArgumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.expressionArgument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionArgument([NotNull] sphereScript99Parser.ExpressionArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.expressionArgument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionArgument([NotNull] sphereScript99Parser.ExpressionArgumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.unquotedLiteralArgument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnquotedLiteralArgument([NotNull] sphereScript99Parser.UnquotedLiteralArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.unquotedLiteralArgument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnquotedLiteralArgument([NotNull] sphereScript99Parser.UnquotedLiteralArgumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.signedArgumentOperand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSignedArgumentOperand([NotNull] sphereScript99Parser.SignedArgumentOperandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.signedArgumentOperand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSignedArgumentOperand([NotNull] sphereScript99Parser.SignedArgumentOperandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.argumentOperand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentOperand([NotNull] sphereScript99Parser.ArgumentOperandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.argumentOperand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentOperand([NotNull] sphereScript99Parser.ArgumentOperandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.argumentBinaryOperation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentBinaryOperation([NotNull] sphereScript99Parser.ArgumentBinaryOperationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.argumentBinaryOperation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentBinaryOperation([NotNull] sphereScript99Parser.ArgumentBinaryOperationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.argumentOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentOperator([NotNull] sphereScript99Parser.ArgumentOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.argumentOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentOperator([NotNull] sphereScript99Parser.ArgumentOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.argumentSubExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentSubExpression([NotNull] sphereScript99Parser.ArgumentSubExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.argumentSubExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentSubExpression([NotNull] sphereScript99Parser.ArgumentSubExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.argumentBinaryOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentBinaryOperator([NotNull] sphereScript99Parser.ArgumentBinaryOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.argumentBinaryOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentBinaryOperator([NotNull] sphereScript99Parser.ArgumentBinaryOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.evalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEvalExpression([NotNull] sphereScript99Parser.EvalExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.evalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEvalExpression([NotNull] sphereScript99Parser.EvalExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.signedEvalOperand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSignedEvalOperand([NotNull] sphereScript99Parser.SignedEvalOperandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.signedEvalOperand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSignedEvalOperand([NotNull] sphereScript99Parser.SignedEvalOperandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.evalOperand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEvalOperand([NotNull] sphereScript99Parser.EvalOperandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.evalOperand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEvalOperand([NotNull] sphereScript99Parser.EvalOperandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.evalBinaryOperation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEvalBinaryOperation([NotNull] sphereScript99Parser.EvalBinaryOperationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.evalBinaryOperation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEvalBinaryOperation([NotNull] sphereScript99Parser.EvalBinaryOperationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.evalOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEvalOperator([NotNull] sphereScript99Parser.EvalOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.evalOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEvalOperator([NotNull] sphereScript99Parser.EvalOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.evalSubExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEvalSubExpression([NotNull] sphereScript99Parser.EvalSubExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.evalSubExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEvalSubExpression([NotNull] sphereScript99Parser.EvalSubExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.evalBinaryOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEvalBinaryOperator([NotNull] sphereScript99Parser.EvalBinaryOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.evalBinaryOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEvalBinaryOperator([NotNull] sphereScript99Parser.EvalBinaryOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.constantExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstantExpression([NotNull] sphereScript99Parser.ConstantExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.constantExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstantExpression([NotNull] sphereScript99Parser.ConstantExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.macroExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMacroExpression([NotNull] sphereScript99Parser.MacroExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.macroExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMacroExpression([NotNull] sphereScript99Parser.MacroExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.macroOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMacroOperator([NotNull] sphereScript99Parser.MacroOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.macroOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMacroOperator([NotNull] sphereScript99Parser.MacroOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.unaryOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryOperator([NotNull] sphereScript99Parser.UnaryOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.unaryOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryOperator([NotNull] sphereScript99Parser.UnaryOperatorContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
