//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /work/sphereScript99.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="sphereScript99Parser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public interface IsphereScript99Visitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile([NotNull] sphereScript99Parser.FileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.section"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSection([NotNull] sphereScript99Parser.SectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.eofSection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEofSection([NotNull] sphereScript99Parser.EofSectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.functionSection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionSection([NotNull] sphereScript99Parser.FunctionSectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.functionSectionHeader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionSectionHeader([NotNull] sphereScript99Parser.FunctionSectionHeaderContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.codeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCodeBlock([NotNull] sphereScript99Parser.CodeBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] sphereScript99Parser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] sphereScript99Parser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.elseIfStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseIfStatement([NotNull] sphereScript99Parser.ElseIfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.elseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseStatement([NotNull] sphereScript99Parser.ElseStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.macro"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacro([NotNull] sphereScript99Parser.MacroContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCall([NotNull] sphereScript99Parser.CallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] sphereScript99Parser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.memberAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberAccess([NotNull] sphereScript99Parser.MemberAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.evalCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEvalCall([NotNull] sphereScript99Parser.EvalCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.nativeMemberAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNativeMemberAccess([NotNull] sphereScript99Parser.NativeMemberAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.nativeArgumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNativeArgumentList([NotNull] sphereScript99Parser.NativeArgumentListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.customMemberAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCustomMemberAccess([NotNull] sphereScript99Parser.CustomMemberAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.chainedMemberAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChainedMemberAccess([NotNull] sphereScript99Parser.ChainedMemberAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.memberName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberName([NotNull] sphereScript99Parser.MemberNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.enclosedArgumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnclosedArgumentList([NotNull] sphereScript99Parser.EnclosedArgumentListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumentList([NotNull] sphereScript99Parser.ArgumentListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument([NotNull] sphereScript99Parser.ArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.expressionArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionArgument([NotNull] sphereScript99Parser.ExpressionArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.quotedLiteralArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuotedLiteralArgument([NotNull] sphereScript99Parser.QuotedLiteralArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.unquotedLiteralArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnquotedLiteralArgument([NotNull] sphereScript99Parser.UnquotedLiteralArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.signedArgumentOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSignedArgumentOperand([NotNull] sphereScript99Parser.SignedArgumentOperandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.argumentOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumentOperand([NotNull] sphereScript99Parser.ArgumentOperandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.argumentBinaryOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumentBinaryOperation([NotNull] sphereScript99Parser.ArgumentBinaryOperationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.argumentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumentOperator([NotNull] sphereScript99Parser.ArgumentOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.argumentSubExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumentSubExpression([NotNull] sphereScript99Parser.ArgumentSubExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.argumentBinaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumentBinaryOperator([NotNull] sphereScript99Parser.ArgumentBinaryOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.evalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEvalExpression([NotNull] sphereScript99Parser.EvalExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.signedEvalOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSignedEvalOperand([NotNull] sphereScript99Parser.SignedEvalOperandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.evalOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEvalOperand([NotNull] sphereScript99Parser.EvalOperandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.evalBinaryOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEvalBinaryOperation([NotNull] sphereScript99Parser.EvalBinaryOperationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.evalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEvalOperator([NotNull] sphereScript99Parser.EvalOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.evalSubExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEvalSubExpression([NotNull] sphereScript99Parser.EvalSubExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.evalBinaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEvalBinaryOperator([NotNull] sphereScript99Parser.EvalBinaryOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.constantExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantExpression([NotNull] sphereScript99Parser.ConstantExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.macroExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacroExpression([NotNull] sphereScript99Parser.MacroExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.macroOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacroOperator([NotNull] sphereScript99Parser.MacroOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sphereScript99Parser.unaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryOperator([NotNull] sphereScript99Parser.UnaryOperatorContext context);
}
