//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /mnt/c/Users/jakub/sources/ultima/SphereSharp/SphereSharp/src/SphereSharp/sphereScript99.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IsphereScript99Listener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public partial class sphereScript99BaseListener : IsphereScript99Listener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.macro"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMacro([NotNull] sphereScript99Parser.MacroContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.macro"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMacro([NotNull] sphereScript99Parser.MacroContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCall([NotNull] sphereScript99Parser.CallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCall([NotNull] sphereScript99Parser.CallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.argumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentList([NotNull] sphereScript99Parser.ArgumentListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.argumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentList([NotNull] sphereScript99Parser.ArgumentListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgument([NotNull] sphereScript99Parser.ArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgument([NotNull] sphereScript99Parser.ArgumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.expressionArgument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionArgument([NotNull] sphereScript99Parser.ExpressionArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.expressionArgument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionArgument([NotNull] sphereScript99Parser.ExpressionArgumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.unquotedLiteralArgument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnquotedLiteralArgument([NotNull] sphereScript99Parser.UnquotedLiteralArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.unquotedLiteralArgument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnquotedLiteralArgument([NotNull] sphereScript99Parser.UnquotedLiteralArgumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.signedOperand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSignedOperand([NotNull] sphereScript99Parser.SignedOperandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.signedOperand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSignedOperand([NotNull] sphereScript99Parser.SignedOperandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.operand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperand([NotNull] sphereScript99Parser.OperandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.operand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperand([NotNull] sphereScript99Parser.OperandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.binaryOperation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinaryOperation([NotNull] sphereScript99Parser.BinaryOperationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.binaryOperation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinaryOperation([NotNull] sphereScript99Parser.BinaryOperationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperator([NotNull] sphereScript99Parser.OperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperator([NotNull] sphereScript99Parser.OperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.constantExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstantExpression([NotNull] sphereScript99Parser.ConstantExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.constantExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstantExpression([NotNull] sphereScript99Parser.ConstantExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.macroExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMacroExpression([NotNull] sphereScript99Parser.MacroExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.macroExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMacroExpression([NotNull] sphereScript99Parser.MacroExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.subExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubExpression([NotNull] sphereScript99Parser.SubExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.subExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubExpression([NotNull] sphereScript99Parser.SubExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.macroOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMacroOperator([NotNull] sphereScript99Parser.MacroOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.macroOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMacroOperator([NotNull] sphereScript99Parser.MacroOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="sphereScript99Parser.constantOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstantOperator([NotNull] sphereScript99Parser.ConstantOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="sphereScript99Parser.constantOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstantOperator([NotNull] sphereScript99Parser.ConstantOperatorContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
